config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :payforms, only: [:index, :edit, :new, :create, :update, :show, :destroy]
  resources :areas, only: [:index, :edit, :new, :create, :update, :show, :destroy]
  resources :outlays, only: [:index, :edit, :new, :create, :update, :show, :destroy]

  resources :payforms do
  	resources :outlays
  end

  resources :areas do
  	resources :outlays
  end

  match 'relatorio', controller: 'outlays', action: 'relatorio', via: 'get'

  root "outlays#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
	has_many :outlays
end

app/models/outlay.rb
class Outlay < ApplicationRecord
	belongs_to :area
	belongs_to :payform
end

app/models/payform.rb
class Payform < ApplicationRecord
	has_many :outlays
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
	before_action :authenticate_user!
	
	def index
		@areas = Area.order :id
	end

	def new
		@area = Area.new
	end

	def create
		@area = Area.new(area_params)

		if @area.save
			flash[:notice] = "Área criada com sucesso"
			redirect_to areas_path
		else
			flash[:notice] = "Erro ao gravar área :#{@area.errors.full_messages.join}"
			redirect_to new_area_path
		end
	end

	def edit
		busca_area
	end

	def update
		busca_area
		valores = area_params
		if @area.update(valores)
  			flash[:notice] = "Área atualizada com sucesso"
  			redirect_to areas_path
		else
  			#render action: "edit"
  			render :edit
		end
	end

	def destroy
	    id = params[:id]
	    if Area.destroy id
	    	flash[:notice] = "Área deletada"
	    	redirect_to areas_path
	    end
	end

	def show
		busca_area
	end

	private	
	def busca_area
		@area = Area.find(params[:id])
	end

	def area_params
      params.require(:area).permit(:area)
    end
end

app/controllers/outlays_controller.rb
class OutlaysController < ApplicationController
	before_action :authenticate_user!

	def index
		search_outlays
	end

	def new
		@outlay = Outlay.new

		@areas = Area.all

		@payforms = Payform.all
	end

	def create
		@outlay = Outlay.new(outlay_params)
		@outlay.user_id = current_user.id

		if @outlay.save
      		redirect_to outlays_path, notice: 'Despesa cadastrada com sucesso.'
    	else
      		redirect_to outlay_path(:new), notice: "Erro ao cadastrar despesa :#{@outlay.errors.full_messages.join}"
    	end
	end

	def edit
		search_outlay
		
		@areas = Area.all

		@payforms = Payform.all
	end

	def update
		search_outlay
		valores = outlay_params
		if @outlay.update(valores)
  			flash[:notice] = "Despesa atualizada com sucesso"
  			redirect_to outlays_path
		else
  			render :edit
		end
	end

	def destroy
	    id = params[:id]
	    if Outlay.destroy id
	    	flash[:notice] = "Despesa deletada"
	    	redirect_to outlays_path
	    end
	end
	
	def relatorio
		search_outlays
		@areas = Area.all
		@payforms = Payform.all
	end

	private
	def search_outlays
		@outlays = Outlay.where(:user_id => current_user.id)
	end

	def search_outlay
		@outlay = Outlay.find(params[:id])
	end

	def outlay_params
      params.require(:outlay).permit(:area_id, :payform_id, :description, :cost, :payment_day)
    end
end

app/controllers/payforms_controller.rb
class PayformsController < ApplicationController
	before_action :authenticate_user!
	
	def index
		@payforms = Payform.order :id
	end

	def new
		@payform = Payform.new
	end

	def create
		@payform = Payform.new(payform_params)

		if @payform.save
			flash[:notice] = "Pagamento criado com sucesso."
			redirect_to payforms_path
		else
			flash[:notice] =  "Erro ao gravar o pagamento :#{@payform.errors.full_messages.join}"
			redirect_to new_payform_path
		end
	end

	def edit
		busca_payform
	end

	def update
		busca_payform
		valores = payform_params
		if @payform.update(valores)
  			flash[:notice] = "Pagamento atualizado com sucesso"
  			redirect_to payforms_path
		else
  			#render action: "edit"
  			render :edit
		end
	end

	def destroy
	    id = params[:id]
	    if Payform.destroy id
	    	flash[:notice] = "Pagamento deletado"
	    	redirect_to payforms_path
	    end
	end

	def show
		busca_payform
	end

	private	
	def busca_payform
		@payform = Payform.find(params[:id])
	end

	def payform_params
      params.require(:payform).permit(:form)
    end

	# Criar as actions new, create, edit, update e delete
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/outlays_helper.rb
module OutlaysHelper
end

app/helpers/payforms_helper.rb
module PayformsHelper
end

app/views/areas/_form.html.erb
<%= form_for @area do |f| %>
	<% @area.errors.full_messages.each do |erro| %>
		<div class="alert alert-danger" role="alert"><%= erro %></div>
	<% end %>

	<div class="form-group">
		<%= f.label :area %>
		<%= f.text_field :area, class: "form-control" %>
	</div>

	<%= f.submit "Salvar", class: "btn btn-primary" %>
<% end %>

app/views/areas/edit.html.erb
<h1>Edição de Área</h1>
<%= render "form" %>
<button class="btn btn-default pull-right"><%= link_to "Voltar", areas_path %></button>

app/views/areas/index.html.erb
<%= link_to "Adicionar", new_area_path, class: "btn btn-default pull-right"%>
<h1>Áreas</h1>                    

<table class="table table-striped table-condensed"> <!-- table-condensed -->
    <thead>
        <tr>
            <th>ID</th>
            <th>Área</th>
            <th class="pull-right">Opções</th>
        </tr>
    </thead>
    <tbody>
        <% @areas.each do |area| %>
        <tr>
            <td><%= area.id %></td>
            <td><%= link_to area.area, area_path(area) %></td>
            <td class="pull-right">            
                <%= link_to " Editar", edit_area_path(area) %>
                 | 
                <%= link_to " Deletar", area, method: :delete, data: { confirm: "Tem certeza que deseja remover \"#{area.area}\"?" } %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/areas/new.html.erb
<h1>Nova Área</h1>
<%= render "form" %>
<button class="btn btn-default pull-right"><%= link_to "Voltar", areas_path %></button>

app/views/areas/show.html.erb
<h1>Despesas gastas em <%= @area.area %></h1>                    

<table class="table table-striped table-condensed"> <!-- table-condensed -->
    <thead>
        <tr>
            <th>ID</th>
            <th>Área</th>
            <th>Pagamento</th>
            <th>Descrição</th>
            <th>Valor</th>
            <th><span class="pull-right">Opções</span></th>
        </tr>
    </thead>
    <tbody>
        <% @area.outlays.each do |outlay| %>
        <tr>
            <td><%= outlay.id %></td>
            <td><%= outlay.area.area %></td>
            <td><%= outlay.payform.form %></td>
            <td><%= outlay.description %></td>
            <td><%= outlay.cost %></td>            
            <td><span class="pull-right">
                <%= link_to "Ver", outlay_path(outlay) %>
                 |        
                <%= link_to " Editar", edit_outlay_path(outlay) %>
                 | 
                <%= link_to " Deletar", edit_outlay_path(outlay) %>
                </span>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>
<button class="btn btn-default pull-right"><%= link_to "Voltar", outlays_path %></button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sumptus</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<nav class="navbar navbar-default">
  	<div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to "Sumptus", root_path, class: "navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Despesas", outlays_path %></li>
        <li><%= link_to "Formas de Pagamento", payforms_path %></li>
        <li><%= link_to "Áreas", areas_path %></li>
        <% if user_signed_in? %><li><%= link_to "Relatório", controller: 'outlays', action: 'relatorio' %></li><% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if user_signed_in? %>
            <%= link_to "Desconectar de " + current_user.email, destroy_user_session_path, method: 'delete' %>
          <% else %>
            <%= link_to "Login", new_user_session_path %>
          <% end %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
  	</nav>
  	<div class="container">
      <% if flash[:notice] %>
        <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
      <% end %>
    	<%= yield %>
    </div>
  </body>
</html>

app/views/outlays/_form.html.erb
<%= form_for @outlay do |f| %>
	<% @outlay.errors.full_messages.each do |erro| %>
    	<div class="alert alert-danger" role="alert"><%= erro %></div>
	<% end %>

	<div class="form-group">
	    <%= f.label :user %>
	    <input class="form-control" id="disabledInput" type="text" placeholder="<%= current_user.email %>" disabled>
	</div>

	<div class="form-group">
	    <%= f.label :area %>
	    <%= f.collection_select :area_id, @areas, :id, :area, {prompt: "Selectiona uma área"}, {class: "form-control"} %>
	</div>

	<div class="form-group">
	    <%= f.label :payform %>
	    <%= f.collection_select :payform_id, @payforms, :id, :form, {prompt: "Selecione um pagamento"}, {class: "form-control"} %>
	</div>

	<div class="form-group">
	    <%= f.label :description %>
	    <%= f.text_area :description, {class: "form-control"}%>
	</div>

	<div class="form-group">
	    <%= f.label :Custo %>
	    <%= f.text_field :cost, {class: "form-control", type: "decimal"}%>
	</div>

	<div class="form-group">
		<%= f.label :Data %>
		<%= f.date_field :payment_day, {class: "form-control"}%>
	</div>
    	<%= f.submit "Gravar", class: "btn btn-primary" %>
    	<%= link_to "Voltar", outlays_path, class: "btn btn-default"%>
	</div>
<% end %>

app/views/outlays/edit.html.erb
<h1>Editar despesa</h1>
<%= render "form" %>

app/views/outlays/index.html.erb
<%= link_to "Adicionar", new_outlay_path, class: "btn btn-default pull-right"%>
<h1>Despesas</h1>

<table class="table table-striped table-condensed"> <!-- table-condensed -->
    <thead>
        <tr>
            <th>ID</th>
            <th>Área</th>
            <th>Pagamento</th>
            <th>Descrição</th>
            <th>Data Pagamento</th>
            <th>Valor</th>
            <th><span class="pull-right">Opções</span></th>
        </tr>
    </thead>
    <tbody>
        <% @outlays.each do |outlay| %>
        <tr>
            <td><%= outlay.id %></td>
            <td><%= link_to outlay.area.area, area_path(outlay.area_id)%></td>
            <td><%= link_to outlay.payform.form, payform_path(outlay.payform_id) %></td>
            <td><%= outlay.description %></td>
            <td><%= outlay.payment_day %></td>
            <td><%= outlay.cost %></td>            
            <td><span class="pull-right">
                <%= link_to " Editar", edit_outlay_path(outlay) %>
                 | 
                <%= link_to " Deletar", outlay, method: :delete, data: { confirm: "Tem certeza que deseja remover \"#{outlay.id}\"?" } %>
                </span>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/outlays/new.html.erb
<h1>Nova despesa</h1>
<%= render "form" %>

app/views/outlays/relatorio.html.erb
<h1>Relatório</h1>
<h3 class="pull-center">Áreas</h3>
<%= pie_chart @outlays.group(:area_id).count %>
<p>Legenda:
<% @areas.each do |area|%>
<%= area.id %> - <%=area.area%> | 
<% end %>
</p>

<h3 class="pull-center">Formas de Pagamento</h3>
<%= pie_chart @outlays.group(:payform_id).count%>
<p>Legenda:
<% @payforms.each do |payform|%>
<%= payform.id %> - <%=payform.form%> | 
<% end %>
</p>

app/views/payforms/_form.html.erb
<%= form_for @payform do |f| %>
	<% @payform.errors.full_messages.each do |erro| %>
    	<div class="alert alert-danger" role="alert"><%= erro %></div>
	<% end %>

	<div class="form-group">
	    <%= f.label :form %>
	    <%= f.text_field :form, class: "form-control" %>
	</div>

    <%= f.submit "Gravar", class: "btn btn-primary" %>
<% end %>

app/views/payforms/edit.html.erb
<h1>Edição de Forma de Pagamento</h1>
<%= render "form" %>
<button class="btn btn-default pull-right"><%= link_to "Voltar", payforms_path %></button>

app/views/payforms/index.html.erb
<%= link_to "Adicionar", new_payform_path, class: "btn btn-default pull-right"%>
<h1>Formas de Pagamento</h1>		            
<table class="table table-striped table-condensed"> <!-- table-condensed -->
    <thead>
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th class="pull-right">Opções</th>
        </tr>
    </thead>
    <tbody>
        <% @payforms.each do |payform| %>
        <tr>
            <td><%= payform.id %></td>
            <td><%= link_to payform.form, payform_path(payform) %></td>
            <td class="pull-right">            
                <%= link_to " Editar", edit_payform_path(payform) %>
                 | 
                <%= link_to " Deletar", payform, method: :delete, data: { confirm: "Tem certeza que deseja remover \"#{payform.form}\"?" } %>
            </td>
          </div>
        </div>
    </td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/payforms/new.html.erb
<h1>Nova Forma de Pagamento</h1>
<%= render "form" %>
<button class="btn btn-default pull-right"><%= link_to "Voltar", payforms_path %></button>

app/views/payforms/show.html.erb
<h1>Despesas pagas com <%= @payform.form %></h1>                    

<table class="table table-striped table-condensed"> <!-- table-condensed -->
    <thead>
        <tr>
            <th>ID</th>
            <th>Área</th>
            <th>Pagamento</th>
            <th>Descrição</th>
            <th>Valor</th>
            <th><span class="pull-right">Opções</span></th>
        </tr>
    </thead>
    <tbody>
        <% @payform.outlays.each do |outlay| %>
        <tr>
            <td><%= outlay.id %></td>
            <td><%= outlay.area.area %></td>
            <td><%= outlay.payform.form %></td>
            <td><%= outlay.description %></td>
            <td><%= outlay.cost %></td>            
            <td><span class="pull-right">
                <%= link_to "Ver", outlay_path(outlay) %>
                 |        
                <%= link_to " Editar", edit_outlay_path(outlay) %>
                 | 
                <%= link_to " Deletar", edit_outlay_path(outlay) %>
                </span>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>
<button class="btn btn-default pull-right"><%= link_to "Voltar", outlays_path %></button>